### ISSUE TITLE
Failed to create new contents.  API failed to connect while resuming due to an unknown error.

### ISSUE THREAD

**Issue by qadirsuh** [googledrive/android-quickstart#17]
Hi there,

I am getting follwing error after capturing the image.

```
11-09 12:27:45.537 6671-6671/genetechsolutions.intentsdemo I/drive-quickstart: Sign in request code
11-09 12:27:45.537 6671-6671/genetechsolutions.intentsdemo I/drive-quickstart: Signed in successfully.
11-09 12:27:52.751 6671-6677/genetechsolutions.intentsdemo W/art: Suspending all threads took: 8.588ms
11-09 12:27:55.041 6671-6671/genetechsolutions.intentsdemo I/drive-quickstart: capture image request code
11-09 12:27:55.041 6671-6671/genetechsolutions.intentsdemo I/drive-quickstart: Image captured successfully.
11-09 12:27:55.042 6671-6671/genetechsolutions.intentsdemo I/drive-quickstart: Creating new contents.
11-09 12:29:47.570 6671-6671/genetechsolutions.intentsdemo W/drive-quickstart: Failed to create new contents.
                                                                               com.google.android.gms.common.api.ApiException: 8: API failed to connect while resuming due to an unknown error.
                                                                                   at com.google.android.gms.common.internal.zzb.zzz(Unknown Source)
                                                                                   at com.google.android.gms.common.api.internal.zzg.zzu(Unknown Source)
                                                                                   at com.google.android.gms.common.api.internal.zze.zzt(Unknown Source)
                                                                                   at com.google.android.gms.common.api.internal.zzbr.zzx(Unknown Source)
                                                                                   at com.google.android.gms.common.api.internal.zzbr.zzahy(Unknown Source)
                                                                                   at com.google.android.gms.common.api.internal.zzbp.handleMessage(Unknown Source)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)

```

I registered my package on google console.
I have updated the google play services too. 

I have also noticed that google play services is crashing after my app installed too. 
whats going on. 
any directions?

**Comment by Ram8948** [comment]
Same issue in my code . have you got any solution?

**Comment by qadirsuh** [comment]
NO @Ram8948

**Comment by gregoireternon** [comment]
Exactly the same issue, and on other project android-demos

**Comment by Bridouille** [comment]
Hey, just ran into the same issue, the issue was that I hadn't enabled the Google Drive API in the developer console.

Somehow for you app to access the API you need to enable it.
https://console.developers.google.com/apis/library/drive.googleapis.com
